### PR TITLE
Show ES query information on Debugbar

### PR DESCRIPTION
**Pull request by mark-juwai**
Show ES query information on Debugbar panels if Debugbar is installed.

### CODE REVIEW

**Comment by xinningsu** [comment]
Instead of creating a new repo, why not just override this trait?

**Comment by mark-juwai** [comment]
How do we reuse it between projects?

**Comment by xinningsu** [comment]
I talk to you in slack since it's public repo.

**Comment by tjoelsson** [comment]
juwai/laravel-elasticquent-debugbar? 😃

**Comment by mark-juwai** [comment]
Move it to an existed repo.

**Pull request closed without merging**
